apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-api
      role: express-api
  template:
    metadata:
      labels:
        app: express-api
        role: express-api
    spec:
      containers:
      - image: mohamadkamal/ci-for-git-ops-pipeline:1.0.13
        name: express-api
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
