apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: default
spec:
  selector:
    app: express-api
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007